modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/builders-tabs/issues"


[[mods]]
modId="builderstabs"
version="1.3.0"
displayName="Builder's Tabs"
itemIcon="minecraft:command_block"
#updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/builders-tabs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/builders-tabs"
logoFile="logo.png"
credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
Adds vanilla special blocks & items without a creative tab and custom player heads into its own tab. Useful for mapmakers and builders.
'''


[[dependencies.builderstabs]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.builderstabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
