modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory (26 is current forge version)
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/builders-tabs/issues" #optional


[[mods]] #mandatory
modId="builderstabs" #mandatory
version="1.2.3" #mandatory
displayName="Builder's Tabs" #mandatory
itemIcon="minecraft:command_block"
#updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/builders-tabs" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/builders-tabs" #optional
logoFile="logo.png" #optional
credits="" #optional
authors="XxRexRaptorxX (RexRaptor)" #optional
description='''
Adds vanilla special blocks & items without a creative tab and custom player heads into its own tab. Useful for mapmakers and builders.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.builderstabs]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.builderstabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
