modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/builders-tabs/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:player_head"
#updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/builders-tabs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/builders-tabs"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''Adds a special creative tab with custom player heads into its own tab. Useful for mapmakers and builders.'''


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

